name: Activate Unity License
on:
  pull_request: {}
  push { branches: [master] }
jobs:
  activate_license:
    runs-on: ubuntu-latest
    steps:
      # Activate license
      - name: Unity - Activate
        uses: webbertakken/unity-activate@v1.2
        with:
          unityVersion: 2020.1.3f1
